config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "welcome/index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

  root to: 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only: [:new, :create]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end


  def edit
  end


  def update
      if @doc.update(doc_params)
          redirect_to @doc
      else
          render 'edit'
      end
  end


  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

   def find_doc
    @doc = Doc.find(params[:id])
   end

   def doc_params
     params.require(:doc).permit(:title, :content)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit , class: "button font-weight-bold"

app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Update

  = render 'form'

  = link_to "Cancel", doc_path(@doc), class: "button font-weight-bold"

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
        .doc
          %p.title= link_to doc.title, doc
          %p.date= time_ago_in_words(doc.created_at)
          %p.content= truncate(doc.content, length: 50)
    - else
      %h2 Something in your mind ?
      %p Write it down, bud ! It can be a brilliant idea :)...
      %button= link_to "New Thought", new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Thought !

  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %h2= simple_format(@doc.content)
  %br
  .buttons
    %center
      = link_to "Fix Doc", edit_doc_path(@doc), class: "button"
      = link_to "Trash It", doc_path(@doc), method: :delete, data: { confirm: "Are you sure you want to remove that ? "}, class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title WiKinimous | Write what's on your mind anonymously !
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to "Wikinimous", root_path, id: "logo"
      %nav
        - if user_signed_in?
          = link_to "New Thought", new_doc_path
          = link_to "Log out", destroy_user_session_path, method: :delete

        - else
          = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 Wikinimous
    %p Write your anonymous thoughts
    %button= link_to "Enter", new_user_registration_path


#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Quote of the day
        %p  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu arcu eu lectus hendrerit tempor. In scelerisque nisi vel est mattis, et dignissim elit commodo. Integer aliquet orci vel placerat dictum. Suspendisse nec finibus mi. Nulla eget sollicitudin nisl, et ultrices leo. Praesent ac venenatis nulla. Curabitur vel risus sapien. Suspendisse fermentum orci id congue sagittis. Etiam dictum urna sed nibh ornare malesuada. Nulla porta elementum orci et convallis. Vestibulum consequat nec libero eu iaculis. Donec imperdiet mattis quam volutpat posuere. Nam sit amet ornare ligula. Sed a nibh dolor. Suspendisse lobortis mauris eget ante interdum imperdiet.

#bottom_cta
  .wrapper
    %h2 Join Us
    %br
    %button= link_to "Join", new_user_registration_path